* libbcel

  #+BEGIN_HTML
      <p>
        <a href="https://stable.melpa.org/#/libbcel">
          <img alt="MELPA Stable" src="https://stable.melpa.org/packages/libbcel-badge.svg"/>
        </a>

        <a href="https://melpa.org/#/libbcel">
          <img alt="MELPA" src="https://melpa.org/packages/libbcel-badge.svg"/>
        </a>

        <a href="https://github.com/DamienCassou/libbcel/actions">
          <img alt="pipeline status" src="https://github.com/DamienCassou/libbcel/actions/workflows/test.yml/badge.svg" />
        </a>
      </p>
  #+END_HTML

** Summary

The package libbcel is an Emacs library to interact with
[[https://basecamp.com][Basecamp]], a project management web application.

** Authentication

To make libbcel work, you first have to give it access to your
Basecamp account. This is done through OAUTH2. If you already have a
client id and secret, skip the next section. Otherwise, keep reading.

*** Obtaining a client id and secret

Login to [[https://basecamp.com/]] and register an application at
[[https://launchpad.37signals.com/integrations]]. You can use whatever
values you want but you should at least:

- check "Basecamp 3" in the "Products" section;
- set the redirect URI as "http://localhost:9321". You can use a
  different port if you want to.

You'll be assigned a client id and client secret. Save that somewhere
so you can skip this step next time.

*** Authenticating

You have a client id, client secret and port number for the redirect
URI (default is 9321). 


** License

See [[file:COPYING][COPYING]]. Copyright (c) 2019 Damien Cassou.

  #+BEGIN_HTML
  <a href="https://liberapay.com/DamienCassou/donate">
    <img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg">
  </a>
  #+END_HTML

#  LocalWords:  Bcel MPD minibuffer
